CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL
);

ALTER TABLE notes ADD COLUMN user_id INT;
ALTER TABLE notes ADD FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE SET NULL;